"""add incremental freshness lifecycle

Revision ID: 4cafdf2faa66
Revises: b83f2d8a6c41
Create Date: 2026-07-18 22:38:04.478329
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4cafdf2faa66'
down_revision: str | None = 'b83f2d8a6c41'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexing_jobs', sa.Column('target_branch', sa.String(length=255), nullable=True))
    op.add_column('indexing_jobs', sa.Column('requested_mode', sa.Enum('incremental', 'full', name='requested_indexing_mode', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('indexing_jobs', sa.Column('actual_mode', sa.Enum('incremental', 'full', name='actual_indexing_mode', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('indexing_jobs', sa.Column('full_rebuild_reason', sa.String(length=64), nullable=True))
    op.add_column('indexing_jobs', sa.Column('refresh_generation', sa.Integer(), server_default='0', nullable=False))
    op.add_column('indexing_jobs', sa.Column('changed_file_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('indexing_jobs', sa.Column('changed_files_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('indexing_jobs', sa.Column('reused_chunk_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('indexing_jobs', sa.Column('reembedded_chunk_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('indexing_jobs', sa.Column('graph_rebuilt', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('repositories', sa.Column('indexed_branch', sa.String(length=255), nullable=True))
    op.add_column('repositories', sa.Column('refresh_generation', sa.Integer(), server_default='0', nullable=False))
    op.add_column('repositories', sa.Column('latest_webhook_commit_sha', sa.String(length=64), nullable=True))
    op.add_column('repositories', sa.Column('last_delivery_status', sa.String(length=32), nullable=True))
    op.add_column('repositories', sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('repository_id', sa.Uuid(), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('indexing_job_id', sa.Uuid(), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('ref', sa.String(length=512), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('before_commit_sha', sa.String(length=64), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('after_commit_sha', sa.String(length=64), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column(
        'webhook_deliveries',
        sa.Column(
            'received_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )
    op.alter_column('webhook_deliveries', 'received_at', server_default=None)
    op.drop_constraint(
        op.f('ck_webhook_deliveries_webhook_delivery_status'),
        'webhook_deliveries',
        type_='check',
    )
    op.alter_column(
        'webhook_deliveries',
        'status',
        existing_type=sa.VARCHAR(length=9),
        type_=sa.String(length=12),
        existing_nullable=False,
        existing_server_default=sa.text("'received'::character varying"),
    )
    op.create_check_constraint(
        op.f('ck_webhook_deliveries_webhook_delivery_status'),
        'webhook_deliveries',
        "status IN ('received', 'queued', 'processing', 'processed', 'completed', "
        "'stale', 'superseded', 'unauthorized', 'retryable', 'ignored', 'failed')",
    )
    op.create_check_constraint(
        op.f('ck_webhook_deliveries_retry_count_nonnegative'),
        'webhook_deliveries',
        'retry_count >= 0',
    )
    for name, expression in (
        ('refresh_generation_nonnegative', 'refresh_generation >= 0'),
        ('changed_file_count_nonnegative', 'changed_file_count >= 0'),
        ('reused_chunk_count_nonnegative', 'reused_chunk_count >= 0'),
        ('reembedded_chunk_count_nonnegative', 'reembedded_chunk_count >= 0'),
    ):
        op.create_check_constraint(op.f(f'ck_indexing_jobs_{name}'), 'indexing_jobs', expression)
    op.create_check_constraint(
        op.f('ck_repositories_refresh_generation_nonnegative'),
        'repositories',
        'refresh_generation >= 0',
    )
    op.drop_index('uq_indexing_jobs_repository_active', table_name='indexing_jobs')
    op.create_index(
        'uq_indexing_jobs_repository_active',
        'indexing_jobs',
        ['repository_id'],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index('ix_webhook_deliveries_repository_received', 'webhook_deliveries', ['repository_id', 'received_at'], unique=False)
    op.create_foreign_key(op.f('fk_webhook_deliveries_indexing_job_id_indexing_jobs'), 'webhook_deliveries', 'indexing_jobs', ['indexing_job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_webhook_deliveries_repository_id_repositories'), 'webhook_deliveries', 'repositories', ['repository_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_webhook_deliveries_repository_id_repositories'), 'webhook_deliveries', type_='foreignkey')
    op.drop_constraint(op.f('fk_webhook_deliveries_indexing_job_id_indexing_jobs'), 'webhook_deliveries', type_='foreignkey')
    op.drop_index('ix_webhook_deliveries_repository_received', table_name='webhook_deliveries')
    op.drop_index('uq_indexing_jobs_repository_active', table_name='indexing_jobs')
    op.execute(
        "WITH ranked AS ("
        "SELECT id, row_number() OVER (PARTITION BY repository_id ORDER BY created_at DESC, id) "
        "AS position FROM indexing_jobs WHERE status IN ('queued', 'running', 'retrying')"
        ") UPDATE indexing_jobs SET status = 'cancelled', "
        "error_code = 'migration_downgrade_superseded', completed_at = now() "
        "FROM ranked WHERE indexing_jobs.id = ranked.id AND ranked.position > 1"
    )
    op.create_index(
        'uq_indexing_jobs_repository_active',
        'indexing_jobs',
        ['repository_id'],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running', 'retrying')"),
    )
    op.drop_constraint(
        op.f('ck_repositories_refresh_generation_nonnegative'),
        'repositories',
        type_='check',
    )
    for name in (
        'reembedded_chunk_count_nonnegative',
        'reused_chunk_count_nonnegative',
        'changed_file_count_nonnegative',
        'refresh_generation_nonnegative',
    ):
        op.drop_constraint(op.f(f'ck_indexing_jobs_{name}'), 'indexing_jobs', type_='check')
    op.drop_constraint(
        op.f('ck_webhook_deliveries_retry_count_nonnegative'),
        'webhook_deliveries',
        type_='check',
    )
    op.execute(
        "UPDATE webhook_deliveries SET status = CASE "
        "WHEN status IN ('processing', 'retryable') THEN 'queued' "
        "WHEN status IN ('completed', 'stale', 'superseded', 'unauthorized') THEN 'processed' "
        "ELSE status END"
    )
    op.drop_constraint(
        op.f('ck_webhook_deliveries_webhook_delivery_status'),
        'webhook_deliveries',
        type_='check',
    )
    op.alter_column(
        'webhook_deliveries',
        'status',
        existing_type=sa.String(length=12),
        type_=sa.String(length=9),
        existing_nullable=False,
        existing_server_default=sa.text("'received'::character varying"),
    )
    op.create_check_constraint(
        op.f('ck_webhook_deliveries_webhook_delivery_status'),
        'webhook_deliveries',
        "status IN ('received', 'queued', 'processed', 'ignored', 'failed')",
    )
    op.drop_column('webhook_deliveries', 'received_at')
    op.drop_column('webhook_deliveries', 'retry_count')
    op.drop_column('webhook_deliveries', 'after_commit_sha')
    op.drop_column('webhook_deliveries', 'before_commit_sha')
    op.drop_column('webhook_deliveries', 'ref')
    op.drop_column('webhook_deliveries', 'indexing_job_id')
    op.drop_column('webhook_deliveries', 'repository_id')
    op.drop_column('repositories', 'last_delivery_at')
    op.drop_column('repositories', 'last_delivery_status')
    op.drop_column('repositories', 'latest_webhook_commit_sha')
    op.drop_column('repositories', 'refresh_generation')
    op.drop_column('repositories', 'indexed_branch')
    op.drop_column('indexing_jobs', 'graph_rebuilt')
    op.drop_column('indexing_jobs', 'reembedded_chunk_count')
    op.drop_column('indexing_jobs', 'reused_chunk_count')
    op.drop_column('indexing_jobs', 'changed_files_json')
    op.drop_column('indexing_jobs', 'changed_file_count')
    op.drop_column('indexing_jobs', 'refresh_generation')
    op.drop_column('indexing_jobs', 'full_rebuild_reason')
    op.drop_column('indexing_jobs', 'actual_mode')
    op.drop_column('indexing_jobs', 'requested_mode')
    op.drop_column('indexing_jobs', 'target_branch')
    # ### end Alembic commands ###
