"""add durable indexing job delivery state

Revision ID: 94b0f7ce7782
Revises: f8eba5464d8c
Create Date: 2026-07-16 17:19:01.258370
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "94b0f7ce7782"
down_revision: str | None = "f8eba5464d8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("indexing_jobs", sa.Column("locked_by", sa.String(length=128), nullable=True))
    op.add_column(
        "indexing_jobs", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "indexing_jobs", sa.Column("last_enqueued_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "indexing_jobs",
        sa.Column("discovered_file_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "indexing_jobs",
        sa.Column("discovered_total_bytes", sa.BigInteger(), server_default="0", nullable=False),
    )
    op.add_column(
        "indexing_jobs",
        sa.Column(
            "skipped_files_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        op.f("ck_indexing_jobs_discovered_file_count_nonnegative"),
        "indexing_jobs",
        "discovered_file_count >= 0",
    )
    op.create_check_constraint(
        op.f("ck_indexing_jobs_discovered_total_bytes_nonnegative"),
        "indexing_jobs",
        "discovered_total_bytes >= 0",
    )
    op.create_index(
        "ix_indexing_jobs_status_next_attempt",
        "indexing_jobs",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "uq_indexing_jobs_repository_active",
        "indexing_jobs",
        ["repository_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running', 'retrying')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_indexing_jobs_repository_active",
        table_name="indexing_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running', 'retrying')"),
    )
    op.drop_index("ix_indexing_jobs_status_next_attempt", table_name="indexing_jobs")
    op.drop_constraint(
        op.f("ck_indexing_jobs_discovered_total_bytes_nonnegative"),
        "indexing_jobs",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_indexing_jobs_discovered_file_count_nonnegative"),
        "indexing_jobs",
        type_="check",
    )
    op.drop_column("indexing_jobs", "skipped_files_json")
    op.drop_column("indexing_jobs", "discovered_total_bytes")
    op.drop_column("indexing_jobs", "discovered_file_count")
    op.drop_column("indexing_jobs", "last_enqueued_at")
    op.drop_column("indexing_jobs", "next_attempt_at")
    op.drop_column("indexing_jobs", "locked_by")
    # ### end Alembic commands ###
