"""add embedding and vector index lifecycle

Revision ID: d06a6455fcd7
Revises: f9389ed2964e
Create Date: 2026-07-16 21:04:37.449736
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd06a6455fcd7'
down_revision: str | None = 'f9389ed2964e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_index_builds',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('building', 'ready', 'active', 'failed', 'superseded', name='index_build_state', native_enum=False, create_constraint=True), server_default='building', nullable=False),
    sa.Column('cleanup_status', sa.Enum('not_required', 'pending', 'complete', name='index_cleanup_status', native_enum=False, create_constraint=True), server_default='not_required', nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('embedding_model_identifier', sa.String(length=255), nullable=False),
    sa.Column('embedding_model_revision', sa.String(length=64), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('preprocessing_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('expected_chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedded_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vector_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleanup_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('embedded_chunk_count >= 0', name=op.f('ck_repository_index_builds_embedded_chunk_count_nonnegative')),
    sa.CheckConstraint('embedding_dimension > 0', name=op.f('ck_repository_index_builds_embedding_dimension_positive')),
    sa.CheckConstraint('expected_chunk_count >= 0', name=op.f('ck_repository_index_builds_expected_chunk_count_nonnegative')),
    sa.CheckConstraint('failed_chunk_count >= 0', name=op.f('ck_repository_index_builds_failed_chunk_count_nonnegative')),
    sa.CheckConstraint('index_version >= 1', name=op.f('ck_repository_index_builds_index_version_positive')),
    sa.CheckConstraint("state != 'active' OR cleanup_status = 'not_required'", name=op.f('ck_repository_index_builds_active_cleanup_not_required')),
    sa.CheckConstraint("state NOT IN ('ready', 'active') OR (expected_chunk_count = embedded_chunk_count AND expected_chunk_count = vector_count AND failed_chunk_count = 0 AND skipped_chunk_count = 0)", name=op.f('ck_repository_index_builds_ready_counts_match')),
    sa.CheckConstraint('skipped_chunk_count >= 0', name=op.f('ck_repository_index_builds_skipped_chunk_count_nonnegative')),
    sa.CheckConstraint('vector_count >= 0', name=op.f('ck_repository_index_builds_vector_count_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['indexing_jobs.id'], name=op.f('fk_repository_index_builds_job_id_indexing_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_index_builds_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_index_builds')),
    sa.UniqueConstraint('job_id', name='uq_repository_index_builds_job'),
    sa.UniqueConstraint('repository_id', 'index_version', name='uq_repository_index_builds_repository_version')
    )
    op.create_index('ix_repository_index_builds_cleanup', 'repository_index_builds', ['cleanup_status', 'updated_at'], unique=False)
    op.create_index('ix_repository_index_builds_repository_state', 'repository_index_builds', ['repository_id', 'state'], unique=False)
    op.create_index('uq_repository_index_builds_repository_active', 'repository_index_builds', ['repository_id'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.add_column('indexing_jobs', sa.Column('target_index_version', sa.Integer(), nullable=True))
    op.add_column('indexing_jobs', sa.Column('embedded_chunk_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('indexing_jobs', sa.Column('vector_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('indexing_jobs', sa.Column('embedding_failed_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('indexing_jobs', sa.Column('embedding_skipped_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('indexing_jobs', sa.Column('embedding_model_identifier', sa.String(length=255), nullable=True))
    op.add_column('indexing_jobs', sa.Column('embedding_model_revision', sa.String(length=64), nullable=True))
    op.add_column('indexing_jobs', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('indexing_jobs', sa.Column('preprocessing_fingerprint', sa.String(length=64), nullable=True))
    op.create_check_constraint(op.f('ck_indexing_jobs_target_index_version_positive'), 'indexing_jobs', 'target_index_version IS NULL OR target_index_version >= 1')
    op.create_check_constraint(op.f('ck_indexing_jobs_embedded_chunk_count_nonnegative'), 'indexing_jobs', 'embedded_chunk_count >= 0')
    op.create_check_constraint(op.f('ck_indexing_jobs_vector_count_nonnegative'), 'indexing_jobs', 'vector_count >= 0')
    op.create_check_constraint(op.f('ck_indexing_jobs_embedding_failed_count_nonnegative'), 'indexing_jobs', 'embedding_failed_count >= 0')
    op.create_check_constraint(op.f('ck_indexing_jobs_embedding_skipped_count_nonnegative'), 'indexing_jobs', 'embedding_skipped_count >= 0')
    op.create_check_constraint(op.f('ck_indexing_jobs_embedding_dimension_positive'), 'indexing_jobs', 'embedding_dimension IS NULL OR embedding_dimension > 0')
    op.add_column('repositories', sa.Column('active_vector_count', sa.Integer(), server_default='0', nullable=False))
    op.create_check_constraint(op.f('ck_repositories_active_vector_count_nonnegative'), 'repositories', 'active_vector_count >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_repositories_active_vector_count_nonnegative'), 'repositories', type_='check')
    op.drop_column('repositories', 'active_vector_count')
    op.drop_constraint(op.f('ck_indexing_jobs_embedding_dimension_positive'), 'indexing_jobs', type_='check')
    op.drop_constraint(op.f('ck_indexing_jobs_embedding_skipped_count_nonnegative'), 'indexing_jobs', type_='check')
    op.drop_constraint(op.f('ck_indexing_jobs_embedding_failed_count_nonnegative'), 'indexing_jobs', type_='check')
    op.drop_constraint(op.f('ck_indexing_jobs_vector_count_nonnegative'), 'indexing_jobs', type_='check')
    op.drop_constraint(op.f('ck_indexing_jobs_embedded_chunk_count_nonnegative'), 'indexing_jobs', type_='check')
    op.drop_constraint(op.f('ck_indexing_jobs_target_index_version_positive'), 'indexing_jobs', type_='check')
    op.drop_column('indexing_jobs', 'preprocessing_fingerprint')
    op.drop_column('indexing_jobs', 'embedding_dimension')
    op.drop_column('indexing_jobs', 'embedding_model_revision')
    op.drop_column('indexing_jobs', 'embedding_model_identifier')
    op.drop_column('indexing_jobs', 'embedding_skipped_count')
    op.drop_column('indexing_jobs', 'embedding_failed_count')
    op.drop_column('indexing_jobs', 'vector_count')
    op.drop_column('indexing_jobs', 'embedded_chunk_count')
    op.drop_column('indexing_jobs', 'target_index_version')
    op.drop_index('ix_repository_index_builds_repository_state', table_name='repository_index_builds')
    op.drop_index('uq_repository_index_builds_repository_active', table_name='repository_index_builds', postgresql_where=sa.text("state = 'active'"))
    op.drop_index('ix_repository_index_builds_cleanup', table_name='repository_index_builds')
    op.drop_table('repository_index_builds')
    # ### end Alembic commands ###
