"""create foundational schema

Revision ID: d2eea490eb59
Revises:
Create Date: 2026-07-16 13:41:34.058710
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d2eea490eb59"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("github_user_id", sa.BigInteger(), nullable=False),
        sa.Column("github_login", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("github_user_id", name=op.f("uq_users_github_user_id")),
    )
    op.create_index("ix_users_github_login", "users", ["github_login"], unique=False)
    op.create_table(
        "webhook_deliveries",
        sa.Column("delivery_id", sa.String(length=255), nullable=False),
        sa.Column("event_name", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "queued",
                "processed",
                "ignored",
                "failed",
                name="webhook_delivery_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="received",
            nullable=False,
        ),
        sa.Column("safe_error_code", sa.String(length=64), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_deliveries")),
        sa.UniqueConstraint("delivery_id", name=op.f("uq_webhook_deliveries_delivery_id")),
    )
    op.create_index(
        "ix_webhook_deliveries_status_created",
        "webhook_deliveries",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "github_installations",
        sa.Column("github_installation_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "user",
                "organization",
                name="github_account_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("account_github_id", sa.BigInteger(), nullable=False),
        sa.Column("account_login", sa.String(length=255), nullable=False),
        sa.Column("installed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                "deleted",
                name="installation_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "permissions_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "repository_selection",
            sa.Enum(
                "all",
                "selected",
                name="repository_selection",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["installed_by_user_id"],
            ["users.id"],
            name=op.f("fk_github_installations_installed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_installations")),
        sa.UniqueConstraint(
            "github_installation_id", name=op.f("uq_github_installations_github_installation_id")
        ),
    )
    op.create_index(
        "ix_github_installations_account",
        "github_installations",
        ["account_github_id", "status"],
        unique=False,
    )
    op.create_table(
        "installation_members",
        sa.Column("installation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "member",
                name="installation_member_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["github_installations.id"],
            name=op.f("fk_installation_members_installation_id_github_installations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_installation_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installation_members")),
        sa.UniqueConstraint(
            "installation_id", "user_id", name="uq_installation_members_installation_user"
        ),
    )
    op.create_index(
        "ix_installation_members_user_installation",
        "installation_members",
        ["user_id", "installation_id"],
        unique=False,
    )
    op.create_table(
        "repositories",
        sa.Column("installation_id", sa.Uuid(), nullable=False),
        sa.Column("github_repository_id", sa.BigInteger(), nullable=False),
        sa.Column("github_owner", sa.String(length=255), nullable=False),
        sa.Column("github_name", sa.String(length=255), nullable=False),
        sa.Column("github_full_name", sa.String(length=512), nullable=False),
        sa.Column("github_url", sa.Text(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("current_remote_sha", sa.String(length=64), nullable=True),
        sa.Column("last_indexed_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("index_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "indexing_status",
            sa.Enum(
                "not_indexed",
                "queued",
                "cloning",
                "discovering",
                "parsing",
                "embedding",
                "building_graph",
                "finalizing",
                "complete",
                "failed",
                "deleting",
                "access_revoked",
                name="repository_indexing_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="not_indexed",
            nullable=False,
        ),
        sa.Column("indexing_progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("indexing_stage", sa.String(length=64), nullable=True),
        sa.Column("indexing_error_code", sa.String(length=64), nullable=True),
        sa.Column("indexing_error_message", sa.String(length=512), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("primary_language", sa.String(length=64), nullable=True),
        sa.Column("last_indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "index_version >= 0", name=op.f("ck_repositories_index_version_nonnegative")
        ),
        sa.CheckConstraint(
            "indexing_progress >= 0 AND indexing_progress <= 100",
            name=op.f("ck_repositories_indexing_progress_range"),
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0",
            name=op.f("ck_repositories_size_bytes_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["github_installations.id"],
            name=op.f("fk_repositories_installation_id_github_installations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint(
            "installation_id", "github_full_name", name="uq_repositories_installation_full_name"
        ),
        sa.UniqueConstraint(
            "installation_id",
            "github_repository_id",
            name="uq_repositories_installation_github_repository",
        ),
    )
    op.create_index(
        "ix_repositories_github_full_name", "repositories", ["github_full_name"], unique=False
    )
    op.create_index(
        "ix_repositories_installation_status",
        "repositories",
        ["installation_id", "indexing_status", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "chat_sessions",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_chat_sessions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_chat_sessions_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_sessions")),
    )
    op.create_index(
        "ix_chat_sessions_creator_updated",
        "chat_sessions",
        ["created_by_user_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_chat_sessions_repository_updated",
        "chat_sessions",
        ["repository_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "indexing_jobs",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "job_type",
            sa.Enum(
                "initial_index",
                "manual_reindex",
                "incremental_reindex",
                "full_rebuild",
                "delete_repository",
                name="indexing_job_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "retrying",
                "complete",
                "failed",
                "cancelled",
                name="indexing_job_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("source_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("target_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("safe_error_message", sa.String(length=512), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_indexing_jobs_attempt_nonnegative")),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name=op.f("ck_indexing_jobs_progress_range")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_indexing_jobs_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_indexing_jobs_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indexing_jobs")),
    )
    op.create_index(
        "ix_indexing_jobs_repository_status",
        "indexing_jobs",
        ["repository_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_indexing_jobs_requester_created",
        "indexing_jobs",
        ["requested_by_user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "symbol_definitions",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("symbol_name", sa.String(length=512), nullable=False),
        sa.Column("qualified_name", sa.String(length=1024), nullable=False),
        sa.Column(
            "symbol_type",
            sa.Enum(
                "function",
                "async_function",
                "class",
                "method",
                "module",
                name="symbol_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "end_line >= start_line", name=op.f("ck_symbol_definitions_line_range_ordered")
        ),
        sa.CheckConstraint(
            "index_version >= 1", name=op.f("ck_symbol_definitions_index_version_positive")
        ),
        sa.CheckConstraint(
            "start_line >= 1", name=op.f("ck_symbol_definitions_start_line_positive")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_symbol_definitions_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbol_definitions")),
        sa.UniqueConstraint(
            "id", "repository_id", "index_version", name="uq_symbol_definitions_identity_scope"
        ),
        sa.UniqueConstraint(
            "repository_id",
            "index_version",
            "file_path",
            "qualified_name",
            "start_line",
            name="uq_symbol_definitions_location",
        ),
    )
    op.create_index(
        "ix_symbol_definitions_content_hash", "symbol_definitions", ["content_hash"], unique=False
    )
    op.create_index(
        "ix_symbol_definitions_repository_version_file",
        "symbol_definitions",
        ["repository_id", "index_version", "file_path"],
        unique=False,
    )
    op.create_index(
        "ix_symbol_definitions_repository_version_name",
        "symbol_definitions",
        ["repository_id", "index_version", "symbol_name"],
        unique=False,
    )
    op.create_table(
        "call_edges",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("index_version", sa.Integer(), nullable=False),
        sa.Column("caller_symbol_id", sa.Uuid(), nullable=False),
        sa.Column("callee_symbol_id", sa.Uuid(), nullable=True),
        sa.Column("unresolved_callee_name", sa.String(length=1024), nullable=True),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("call_line", sa.Integer(), nullable=False),
        sa.Column(
            "resolution_type",
            sa.Enum(
                "exact_same_file",
                "exact_direct_import",
                "qualified_module",
                "probable_method",
                "unresolved",
                name="call_resolution_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum(
                "high",
                "medium",
                "low",
                name="call_confidence",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("call_line >= 1", name=op.f("ck_call_edges_call_line_positive")),
        sa.CheckConstraint(
            "callee_symbol_id IS NOT NULL OR unresolved_callee_name IS NOT NULL",
            name=op.f("ck_call_edges_callee_or_unresolved_required"),
        ),
        sa.CheckConstraint("index_version >= 1", name=op.f("ck_call_edges_index_version_positive")),
        sa.ForeignKeyConstraint(
            ["callee_symbol_id", "repository_id", "index_version"],
            [
                "symbol_definitions.id",
                "symbol_definitions.repository_id",
                "symbol_definitions.index_version",
            ],
            name="fk_call_edges_callee_symbol_scope",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["caller_symbol_id", "repository_id", "index_version"],
            [
                "symbol_definitions.id",
                "symbol_definitions.repository_id",
                "symbol_definitions.index_version",
            ],
            name="fk_call_edges_caller_symbol_scope",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_call_edges_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_edges")),
    )
    op.create_index(
        "ix_call_edges_repository_version_callee",
        "call_edges",
        ["repository_id", "index_version", "callee_symbol_id"],
        unique=False,
    )
    op.create_index(
        "ix_call_edges_repository_version_caller",
        "call_edges",
        ["repository_id", "index_version", "caller_symbol_id"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user",
                "assistant",
                "system_event",
                name="chat_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "answer_status",
            sa.Enum(
                "answered",
                "partially_answered",
                "insufficient_evidence",
                "stale_index",
                "tool_failure",
                "unsupported_question",
                name="answer_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "confidence",
            sa.Enum(
                "high",
                "medium",
                "low",
                name="answer_confidence",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "tool_trace_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "evidence_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("indexed_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(content) > 0", name=op.f("ck_chat_messages_content_nonempty")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
            name=op.f("fk_chat_messages_session_id_chat_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        "ix_chat_messages_session_created",
        "chat_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "usage_records",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("repository_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("embedding_units", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "embedding_units IS NULL OR embedding_units >= 0",
            name=op.f("ck_usage_records_embedding_units_nonnegative"),
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name=op.f("ck_usage_records_estimated_cost_nonnegative"),
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_usage_records_input_tokens_nonnegative"),
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0",
            name=op.f("ck_usage_records_latency_nonnegative"),
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_usage_records_output_tokens_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_usage_records_repository_id_repositories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
            name=op.f("fk_usage_records_session_id_chat_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_usage_records_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    op.create_index(
        "ix_usage_records_repository_created",
        "usage_records",
        ["repository_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_usage_records_user_created", "usage_records", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_records_user_created", table_name="usage_records")
    op.drop_index("ix_usage_records_repository_created", table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index("ix_chat_messages_session_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_call_edges_repository_version_caller", table_name="call_edges")
    op.drop_index("ix_call_edges_repository_version_callee", table_name="call_edges")
    op.drop_table("call_edges")
    op.drop_index("ix_symbol_definitions_repository_version_name", table_name="symbol_definitions")
    op.drop_index("ix_symbol_definitions_repository_version_file", table_name="symbol_definitions")
    op.drop_index("ix_symbol_definitions_content_hash", table_name="symbol_definitions")
    op.drop_table("symbol_definitions")
    op.drop_index("ix_indexing_jobs_requester_created", table_name="indexing_jobs")
    op.drop_index("ix_indexing_jobs_repository_status", table_name="indexing_jobs")
    op.drop_table("indexing_jobs")
    op.drop_index("ix_chat_sessions_repository_updated", table_name="chat_sessions")
    op.drop_index("ix_chat_sessions_creator_updated", table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index("ix_repositories_installation_status", table_name="repositories")
    op.drop_index("ix_repositories_github_full_name", table_name="repositories")
    op.drop_table("repositories")
    op.drop_index("ix_installation_members_user_installation", table_name="installation_members")
    op.drop_table("installation_members")
    op.drop_index("ix_github_installations_account", table_name="github_installations")
    op.drop_table("github_installations")
    op.drop_index("ix_webhook_deliveries_status_created", table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index("ix_users_github_login", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
