"""add multi-provider auth and public repositories

Revision ID: da6b47f8cd61
Revises: 4cafdf2faa66
Create Date: 2026-07-19 17:48:01.315204
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'da6b47f8cd61'
down_revision: str | None = '4cafdf2faa66'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'github', name='auth_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_identities_subject')
    )
    op.create_index('ix_auth_identities_user', 'auth_identities', ['user_id'], unique=False)
    op.create_index('ix_auth_identities_verified_email', 'auth_identities', ['provider_email', 'email_verified'], unique=False)
    op.execute(
        "INSERT INTO auth_identities "
        "(id, user_id, provider, provider_subject, provider_email, email_verified, "
        "created_at, updated_at) "
        "SELECT md5('repolume-auth-github:' || id::text)::uuid, id, 'github', "
        "github_user_id::text, email, false, created_at, updated_at FROM users"
    )
    op.create_table('user_repositories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_user_repositories_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_repositories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_repositories')),
    sa.UniqueConstraint('user_id', 'repository_id', name='uq_user_repositories_membership')
    )
    op.create_index('ix_user_repositories_repository', 'user_repositories', ['repository_id'], unique=False)
    op.add_column('oauth_states', sa.Column('provider', sa.Enum('google', 'github', name='oauth_provider', native_enum=False, create_constraint=True), server_default='github', nullable=False))
    op.add_column('oauth_states', sa.Column('flow', sa.Enum('sign_in', 'link', name='oauth_flow', native_enum=False, create_constraint=True), server_default='sign_in', nullable=False))
    op.add_column('oauth_states', sa.Column('nonce_hash', sa.String(length=64), nullable=True))
    op.add_column('oauth_states', sa.Column('intended_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_oauth_states_intended_user_id_users'), 'oauth_states', 'users', ['intended_user_id'], ['id'], ondelete='CASCADE')
    op.add_column('repositories', sa.Column('access_mode', sa.Enum('public', 'github_installation', name='repository_access_mode', native_enum=False, create_constraint=True), server_default='github_installation', nullable=False))
    op.add_column('repositories', sa.Column('visibility_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('repositories', 'installation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_repositories_access_mode', 'repositories', ['access_mode', 'deleted_at'], unique=False)
    op.create_index('uq_repositories_public_github_repository', 'repositories', ['github_repository_id'], unique=True, postgresql_where=sa.text("access_mode = 'public'"))
    op.create_check_constraint(
        op.f('ck_repositories_access_mode_installation_valid'),
        'repositories',
        "(access_mode = 'public' AND installation_id IS NULL AND is_private = false) OR "
        "(access_mode = 'github_installation' AND installation_id IS NOT NULL)",
    )
    op.alter_column('users', 'github_user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'github_login',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$ BEGIN "
        "IF EXISTS (SELECT 1 FROM repositories WHERE access_mode = 'public') THEN "
        "RAISE EXCEPTION 'cannot downgrade while public repositories exist'; END IF; "
        "IF EXISTS (SELECT 1 FROM users WHERE github_user_id IS NULL OR github_login IS NULL) THEN "
        "RAISE EXCEPTION 'cannot downgrade while non-GitHub users exist'; END IF; "
        "END $$"
    )
    op.alter_column('users', 'github_login',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'github_user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index('uq_repositories_public_github_repository', table_name='repositories', postgresql_where=sa.text("access_mode = 'public'"))
    op.drop_index('ix_repositories_access_mode', table_name='repositories')
    op.drop_constraint(
        op.f('ck_repositories_access_mode_installation_valid'),
        'repositories',
        type_='check',
    )
    op.alter_column('repositories', 'installation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('repositories', 'visibility_checked_at')
    op.drop_column('repositories', 'access_mode')
    op.drop_constraint(op.f('fk_oauth_states_intended_user_id_users'), 'oauth_states', type_='foreignkey')
    op.drop_column('oauth_states', 'intended_user_id')
    op.drop_column('oauth_states', 'nonce_hash')
    op.drop_column('oauth_states', 'flow')
    op.drop_column('oauth_states', 'provider')
    op.drop_index('ix_user_repositories_repository', table_name='user_repositories')
    op.drop_table('user_repositories')
    op.drop_index('ix_auth_identities_verified_email', table_name='auth_identities')
    op.drop_index('ix_auth_identities_user', table_name='auth_identities')
    op.drop_table('auth_identities')
    # ### end Alembic commands ###
